"""
generate_images.py — AeoniumGlow Shorts Pipeline
Generates one image per scene using Replicate Flux Dev.
Falls back to xAI (Aurora / grok-2-image) if Replicate fails.

Image prompts come from (in priority order):
  1. manifest.json scene["prompt"]  ← set manually or by generate_script.py
  2. script_prompts.json            ← generated by generate_script.py
  3. Auto-generated from scene["script"] via OpenAI

Usage:
    python generate_images.py --project short-04
    python generate_images.py --project short-04 --force   # re-generate existing images

Requires:
    pip install replicate openai requests pillow
    REPLICATE_API_TOKEN  in environment
    XAI_API_KEY          in environment (fallback)
    OPENAI_API_KEY       in environment (auto-prompt generation)
"""

import argparse
import json
import os
import re
import sys
import time
import urllib.request
from collections import Counter
from concurrent.futures import ThreadPoolExecutor, as_completed

from config_loader import load_config  # single source of truth, see config_loader.py
from console_encoding import ensure_utf8_console
ensure_utf8_console()

# ── optional .env support ─────────────────────────────────────────────────────
try:
    from dotenv import load_dotenv
    load_dotenv()
except ImportError:
    pass


def orientation_phrase(config: dict) -> str:
    """
    'image_aspect_ratio' -> the camera-descriptor phrase used throughout the LLM
    prompts below. Defaults to "9:16" (Shorts) when unset, so any caller that
    doesn't pass a longform-style config keeps today's exact wording.
    """
    aspect = (config or {}).get("image_aspect_ratio", "9:16")
    return "16:9 widescreen" if aspect == "16:9" else "9:16 vertical"


def camera_descriptor_block(config: dict) -> str:
    """Five camera-shot phrasings, prefixed with the config's orientation phrase."""
    o = orientation_phrase(config)
    return (
        f"  'A {o} extreme close-up of'\n"
        f"  'A {o} close-up of'\n"
        f"  'A {o} mid-shot of'\n"
        f"  'A {o} cinematic shot of'\n"
        f"  'A tall {o} shot of'"
    )


def base_project_dir(project_dir: str, config: dict = None) -> str:
    """
    Strip a variant suffix ("Myths_S1_yt" → "Myths_S1") so shared, variant-agnostic
    assets can live once in the base project folder instead of being copied into
    every variant. Only strips a suffix that is a configured variant name AND whose
    base folder actually exists, so genuine project names ending in "_S1" are safe.
    Returns project_dir unchanged when there is nothing to strip.
    """
    variants = (config or {}).get("variants", {})
    for vname in variants:
        suffix = f"_{vname}"
        if project_dir.endswith(suffix):
            candidate = project_dir[: -len(suffix)]
            if os.path.isdir(candidate):
                return candidate
    return project_dir


def _read_pointer_file(path: str) -> str:
    """
    Read a source_doc.path pointer file: the first non-blank, non-comment line is
    an absolute (or project-relative) path to the canonical source document.
    Returns "" when the file has no usable line.
    """
    with open(path, "r", encoding="utf-8", errors="ignore") as f:
        for line in f:
            line = line.strip()
            if line and not line.startswith("#"):
                return line
    return ""


def resolve_source_doc_path(project_dir: str, explicit_path: str = None,
                            config: dict = None) -> str:
    """
    Resolve the canonical source document for a project.
    Priority:
      1. --source-doc explicit path (absolute, or relative to project_dir)
      2. {project_dir}/source_doc.path        ← pointer to a doc stored elsewhere
      3. {base_project_dir}/source_doc.path   ← pointer shared by all variants
      4. {project_dir}/source_doc/*.{md,txt}       (first match)
      5. {base_project_dir}/source_doc/*.{md,txt}  (first match)
    Returns None if nothing is found.

    Steps 3 and 5 matter because run_pipeline.py passes the *variant* folder
    ("Myths_S1_yt") while source docs live in the base folder ("Myths_S1").
    """
    if explicit_path:
        path = explicit_path if os.path.isabs(explicit_path) else os.path.join(project_dir, explicit_path)
        if os.path.isfile(path):
            return path
        print(f"   ⚠️  --source-doc is not a readable file: {path}")
        return None

    base_dir = base_project_dir(project_dir, config)
    search_dirs = [project_dir] if base_dir == project_dir else [project_dir, base_dir]

    # Pointer files first — an explicit pointer beats an incidental local copy.
    for d in search_dirs:
        pointer = os.path.join(d, "source_doc.path")
        if not os.path.isfile(pointer):
            continue
        target = _read_pointer_file(pointer)
        if not target:
            print(f"   ⚠️  Empty source_doc.path: {pointer}")
            continue
        if not os.path.isabs(target):
            target = os.path.join(d, target)
        if os.path.isfile(target):
            return target
        reason = "is a folder, not a file" if os.path.isdir(target) else "does not exist"
        print(f"   ⚠️  source_doc.path target {reason}: {target}")
        print(f"       (pointer: {pointer})")

    # Fall back to a doc copied into the project.
    for d in search_dirs:
        source_doc_dir = os.path.join(d, "source_doc")
        if os.path.isdir(source_doc_dir):
            candidates = sorted(
                f for f in os.listdir(source_doc_dir)
                if f.lower().endswith((".md", ".txt"))
            )
            if candidates:
                return os.path.join(source_doc_dir, candidates[0])

    return None


def load_source_doc(project_dir: str, explicit_path: str = None, max_chars: int = 16000,
                    config: dict = None) -> str:
    """
    Load the long-form source document for story-aware prompt generation.
    See resolve_source_doc_path() for the lookup order. Returns "" if none found.
    """
    path = resolve_source_doc_path(project_dir, explicit_path, config)

    if not path:
        return ""

    with open(path, "r", encoding="utf-8", errors="ignore") as f:
        text = f.read()

    if len(text) > max_chars:
        text = text[:max_chars] + "\n...[truncated]"

    print(f"   📖 Source doc loaded: {path} ({len(text)} chars)")
    return text


def load_brand_brief(scripts_dir: str, max_chars: int = 16000) -> str:
    """
    Load AEONIUM_GLOW_BRAND_BRIEF.txt from the pipeline root, if present.
    This is the authoritative brand identity doc (tone, visual rules, species
    library, terminology) — always included in prompt generation regardless
    of whether a project has its own source_doc, since it's channel-wide,
    not project-specific. Returns "" if the file doesn't exist.
    """
    path = os.path.join(scripts_dir, "AEONIUM_GLOW_BRAND_BRIEF.txt")
    if not os.path.exists(path):
        return ""
    with open(path, "r", encoding="utf-8", errors="ignore") as f:
        text = f.read()
    if len(text) > max_chars:
        text = text[:max_chars] + "\n...[truncated]"
    return text


# ── prompt builder ────────────────────────────────────────────────────────────

def build_prompt_map(project_dir: str, scenes: list, prompts_file: str = None) -> dict:
    """
    Build a dict mapping scene_id → image prompt.
    Priority: manifest prompt > prompts file (script_prompts.json, or an
    explicit --prompts-file override) > None (will auto-generate).

    The prompts file can key entries either by "scene_id" (preferred, robust
    to reordering) or fall back to positional-index matching against
    "segment" for the original hand-written script_prompts.json format.
    """
    # Resolve which prompts file to read: explicit override > default script_prompts.json
    if prompts_file:
        prompts_path = prompts_file if os.path.isabs(prompts_file) else os.path.join(project_dir, prompts_file)
    else:
        prompts_path = os.path.join(project_dir, "script_prompts.json")

    segment_prompts = []
    by_scene_id = {}
    if os.path.exists(prompts_path):
        with open(prompts_path, "r", encoding="utf-8") as f:
            data = json.load(f)
        segment_prompts = data.get("image_prompts", [])
        # override_prompt > auto_prompt > legacy "prompt" (old script_prompts.json format,
        # pre-dry-run-review). A blank override_prompt is the DOCUMENTED normal case — this
        # file's own dry-run output tells the user to leave it blank to use auto_prompt as-is
        # (see the dry-run print block below) — so auto_prompt must be checked here, not
        # skipped straight to the legacy key. Missing this let every shot a human correctly
        # left un-overridden fall out of by_scene_id entirely, silently discarding the
        # reviewed prompt and re-generating a fresh, unreviewed one instead — caught on
        # Etiolation_S1 (2026-08-06): all 10 item shots plus 4 others got a second,
        # independent OpenAI call that cross-contaminated content between shots. Mirrors the
        # fallback chain make_contact_sheet.py's pick() already used correctly.
        by_scene_id = {
            p["scene_id"]: (p.get("override_prompt") or p.get("auto_prompt") or p.get("prompt", "")).strip()
            for p in segment_prompts
            if p.get("scene_id") and (p.get("override_prompt") or p.get("auto_prompt") or p.get("prompt", "")).strip()
        }
        print(f"   📋 Using prompts file: {prompts_path} ({len(segment_prompts)} entries)")
    elif prompts_file:
        # An explicit --prompts-file is a deliberate instruction to use THIS file — usually
        # a human-approved checkpoint (prompts_review.json with real override_prompt values).
        # Silently falling back to manifest/auto-generation here means burning API cost on
        # fresh, unreviewed prompts while looking like the approved ones were used — exactly
        # the "reported success while doing nothing" failure class this pipeline has been bitten
        # by repeatedly (shorts_session.md: source docs never loading, 8/9 scenes dropped,
        # --prompts-file ignored). A relative path from run_pipeline.py used to be the only
        # known cause (bug #16, fixed there) — but any other path-resolution failure (a shell
        # mangling backslashes, a typo, a deleted file) hits this exact code path unprotected.
        # Refuse instead of guessing: the caller asked for a specific file, so treat "not found"
        # as an error, not a hint to go generate something else.
        print(f"❌ --prompts-file not found: {prompts_path}")
        print(f"   (as passed: {prompts_file!r})")
        print(f"   Refusing to silently fall back to auto-generation — that would replace")
        print(f"   whatever checkpoint-approved prompts this file represents with fresh,")
        print(f"   unreviewed ones, at real API cost, while reporting success.")
        print(f"   Fix the path (or drop --prompts-file if you really want auto-generation).")
        sys.exit(1)

    # An explicit --prompts-file is a deliberate override and outranks whatever is
    # already in the manifest. Without this, --dry-run-prompts writes auto-prompts
    # into manifest.json, and every later --prompts-file run is silently ignored —
    # which also breaks the documented "fix a wrong image" recovery workflow.
    # The implicit script_prompts.json default keeps its original lower priority.
    explicit_override = bool(prompts_file)
    overridden = []

    prompt_map = {}
    for i, scene in enumerate(scenes):
        scene_id = scene["id"]
        # Scenes sharing a visual_group_id ("shots") are keyed in the prompts file by
        # that group id, not by each member's own scene id — build_prompts_map's shot
        # logic (below) and generate_override_prompts.py both write overrides this way.
        # Checking only scene_id here meant an explicit --prompts-file override was
        # silently ignored for every grouped scene, falling through to the stale
        # manifest prompt instead — caught on Propagation_S1_yt's group-01.
        lookup_key = scene.get("visual_group_id") or scene_id

        # 1. Explicit --prompts-file entry (highest priority)
        if explicit_override and lookup_key in by_scene_id:
            prompt_map[scene_id] = by_scene_id[lookup_key]
            if scene.get("prompt") and scene["prompt"].strip() != by_scene_id[lookup_key]:
                overridden.append(scene_id)
            continue

        # 2. Manifest-level prompt
        if scene.get("prompt"):
            prompt_map[scene_id] = scene["prompt"]
            continue

        # 3. Match from prompts file — by scene_id/group id if available, else by position
        if lookup_key in by_scene_id:
            prompt_map[scene_id] = by_scene_id[lookup_key]
            continue
        if i < len(segment_prompts):
            p = segment_prompts[i]
            prompt_map[scene_id] = p.get("prompt", "")
            if prompt_map[scene_id]:
                continue

        # 4. Will auto-generate below
        prompt_map[scene_id] = None

    if overridden:
        print(f"   ↪  --prompts-file overrides manifest prompt for {len(overridden)} scene(s): "
              f"{', '.join(overridden)}")

    return prompt_map


def auto_generate_prompt(scene_script: str, config: dict, source_doc: str = "", brand_brief: str = "") -> str:
    """
    Use OpenAI to:
    1. Pick the most appropriate approved species for the scene
    2. Generate a full image prompt (orientation per config["image_aspect_ratio"])
       with that species injected

    If source_doc is provided (the long-form video source document), it's given
    to the model as story context so prompts are narrative-aware rather than
    generated from the short narration line alone. brand_brief (if provided) is
    the channel's full AEONIUM_GLOW_BRAND_BRIEF.txt — authoritative tone/visual
    identity context.
    """
    try:
        from openai import OpenAI
        client = OpenAI(api_key=os.environ.get("OPENAI_API_KEY"))

        style_template = config.get(
            "image_style_template",
            "Warm cinematic macro photography of [SPECIES]. Shallow depth of field, natural golden-hour light. "
            "Terracotta pots, linen surfaces. Human hands and faces working with plants are welcome. No text, no logos. Photorealistic."
        )
        species_library = config.get("subjects", {})
        species_list = "\n".join(
            f"- {name} ({info['common']}): {info['use_for']}"
            for name, info in species_library.items()
        )

        brand_brief_block = (
            f"\n\nCHANNEL BRAND BRIEF (authoritative — overrides any general instinct below if they conflict):\n"
            f"\"\"\"\n{brand_brief}\n\"\"\"\n"
            if brand_brief else ""
        )

        source_doc_block = (
            f"\n\nFULL VIDEO SOURCE DOCUMENT (background/context only — do not quote it, "
            f"use it to understand what point this scene is illustrating within the "
            f"larger story, and to keep species/props/setting consistent across scenes):\n"
            f"\"\"\"\n{source_doc}\n\"\"\"\n"
            if source_doc else ""
        )

        response = client.chat.completions.create(
            model="gpt-4o-mini",
            messages=[{
                "role": "system",
                "content": (
                    "You write image generation prompts for a succulent care YouTube Shorts channel called Aeonium Glow.\n\n"
                    "FUNDAMENTAL CONSTRAINT — LITERAL VISUAL TRANSLATION ONLY:\n"
                    "You are a literal visual translator, not a storyteller. Describe a single frozen, static frame "
                    "showing exactly what the narration states — no more, no less. Describe ONLY the physical objects "
                    "and environment explicitly present in the narration. DO NOT infer intent, consequence, or fix: "
                    "if the narration says 'dry, puckered leaves', describe dry puckered leaves — do NOT add a person "
                    "watering them or imply water is coming. A scene about dehydration shows a dehydrated plant, period. "
                    "Exception: if the narration explicitly says an action IS ALREADY HAPPENING (e.g. 'water pours from "
                    "the drainage hole'), show it in progress — that is still literal translation, not inference.\n\n"
                    "STEP 1 — Pick the most appropriate species from this approved list based on the narration:\n"
                    f"{species_list}\n\n"
                    "Default: if the scene is a general watering or soil demo with no specific species, use Echeveria elegans (Mexican Snowball).\n"
                    "NEVER use the generic word 'succulent' without a specific species name.\n\n"
                    "STEP 2 — Build the image prompt using this template (replace [SPECIES] with the chosen species name + common name):\n"
                    f"{style_template}\n\n"
                    "STEP 3 — Prepend the best camera descriptor for the scene:\n"
                    f"{camera_descriptor_block(config)}\n\n"
                    "Add highly specific visual detail — action, texture, sensory detail, lighting.\n"
                    "  Good: 'dark, damp soil particles clinging to the skin, visually indicating moisture'\n"
                    "  Bad: 'person touching soil'\n\n"
                    "Always specify lighting. Include props where natural: terracotta pots, copper or brass watering cans, wooden skewers, linen surfaces.\n"
                    "Show a real person genuinely engaged in the craft — hands AND faces are both welcome and encouraged. "
                    "A face can be partially visible, in profile, or looking down at the work — natural and candid, "
                    "like someone caught mid-task, not posed for the camera. Don't default to isolated hand-only shots "
                    "when a fuller, more human shot would read better. No text overlays, no logos.\n\n"
                    "Use the full source document (if provided below) to understand the biological/narrative "
                    "point this specific line is making, so the visual matches the deeper explanation — not just "
                    "the surface words of the narration line.\n\n"
                    "Output only the final prompt. No commentary."
                    f"{brand_brief_block}"
                    f"{source_doc_block}"
                )
            }, {
                "role": "user",
                "content": f"Write one image prompt for this narration line:\n\n\"{scene_script}\""
            }],
            temperature=0.6,
        )
        return response.choices[0].message.content.strip()

    except Exception as e:
        template = config.get(
            "image_style_template",
            "Warm cinematic macro photography of [SPECIES]. Photorealistic."
        )
        fallback_style = template.replace("[SPECIES]", "Echeveria elegans (Mexican Snowball)")
        return f"A {orientation_phrase(config)} cinematic shot of {scene_script.strip()}. {fallback_style}"


def auto_generate_prompts_batch(scenes: list, config: dict, source_doc: str = "",
                                brand_brief: str = "", extra_instruction: str = "") -> dict:
    """
    Generate image prompts for ALL scenes in a single OpenAI call, so the model
    has full visibility into what species/settings/lighting it already used in
    earlier scenes and can deliberately rotate through the approved species
    library instead of defaulting to the same species every time (which is
    what happens when each scene is generated in isolation).

    scenes: list of {"id": ..., "script": ...} dicts, in narrative order.
    brand_brief: full AEONIUM_GLOW_BRAND_BRIEF.txt content, if available — the
    authoritative channel identity doc (tone, visual rules, species library).
    extra_instruction: additional corrective text appended for a validation/
    retry pass (e.g. "these settings are already overused, don't repeat them").
    Returns: dict mapping scene_id -> prompt string. Falls back to the
    per-scene generator (and its own fallback) for any scene the batch call
    fails to produce.
    """
    try:
        from openai import OpenAI
        import json as _json
        client = OpenAI(api_key=os.environ.get("OPENAI_API_KEY"))

        style_template = config.get(
            "image_style_template",
            "Warm cinematic macro photography of [SPECIES]. Shallow depth of field, natural golden-hour light. "
            "Terracotta pots, linen surfaces. Human hands and faces working with plants are welcome. No text, no logos. Photorealistic."
        )
        species_library = config.get("subjects", {})
        species_list = "\n".join(
            f"- {name} ({info['common']}): {info['use_for']}"
            for name, info in species_library.items()
        )

        brand_brief_block = (
            f"\n\nCHANNEL BRAND BRIEF (authoritative — this overrides any general filmmaking "
            f"instinct below if the two ever conflict):\n\"\"\"\n{brand_brief}\n\"\"\"\n"
            if brand_brief else ""
        )

        source_doc_block = (
            f"\n\nFULL VIDEO SOURCE DOCUMENT (background/context only — do not quote it, "
            f"use it to understand what point each scene is illustrating within the "
            f"larger story):\n\"\"\"\n{source_doc}\n\"\"\"\n"
            if source_doc else ""
        )

        extra_instruction_block = f"\n\nCORRECTION FOR THIS PASS:\n{extra_instruction}\n" if extra_instruction else ""

        scenes_block = "\n".join(
            f'{i}. [{s["id"]}] "{s["script"]}"' for i, s in enumerate(scenes, 1)
        )

        response = client.chat.completions.create(
            model="gpt-4o-mini",
            response_format={"type": "json_object"},
            messages=[{
                "role": "system",
                "content": (
                    "You write image generation prompts for a succulent care YouTube Shorts channel called Aeonium Glow.\n\n"
                    "You will receive ALL scenes of one video's narration, in order. Write one image prompt per scene.\n\n"
                    "FUNDAMENTAL CONSTRAINT — LITERAL VISUAL TRANSLATION ONLY:\n"
                    "You are a literal visual translator, not a storyteller. Your job is to describe a single frozen, "
                    "static frame that shows exactly what the narration states — no more, no less.\n"
                    "  - Describe ONLY the physical objects and environment that are explicitly present in the narration.\n"
                    "  - DO NOT infer intent, consequence, fix, backstory, or future state. If the narration says "
                    "'dry, puckered leaves', describe dry puckered leaves — do NOT add a person watering them, a "
                    "watering can nearby, or any suggestion that water is coming. The plant is in its current state; "
                    "that is the entire story of this frame.\n"
                    "  - This is the most common failure mode in automated pipelines: narration describes a problem "
                    "(dehydration, pests, rot) and the model 'helpfully' shows the solution (watering, spraying, "
                    "repotting). Resist this entirely. A scene about dehydration shows a dehydrated plant, period.\n"
                    "  - The action rule (STEP 2.5 below) is the ONLY exception: if the narration explicitly says "
                    "an action IS ALREADY HAPPENING (e.g. 'water pours from the drainage hole'), show it in progress. "
                    "That is still literal translation — the action is stated, not inferred.\n\n"
                    "STEP 0 — Before writing any prompts, silently extract facts from each scene's narration. "
                    "For each scene, identify:\n"
                    "  (a) WHAT IS EXPLICITLY STATED: physical objects, plant state, actions currently happening.\n"
                    "  (b) WHAT IS EXPLICITLY ABSENT: anything NOT mentioned — no watering if narration doesn't say "
                    "watering, no pests if narration doesn't say pests, no nighttime if narration doesn't say night, "
                    "no drainage hole if narration doesn't mention it.\n"
                    "  (c) TIME OF DAY: does the narration mention night, a specific hour (e.g. 3 a.m.), or darkness? "
                    "If yes, the image MUST use moonlight/night atmosphere. If narration is silent on time, default to "
                    "warm daylight.\n"
                    "Do this extraction silently (do not output it). Then use only what is in column (a) to build each prompt. "
                    "Never add column (b) items to the prompt.\n\n"
                    "STEP 1 — Across the FULL set of scenes, deliberately rotate through this approved species list "
                    "so consecutive scenes don't repeat the same species. Pick based on each scene's narration and "
                    "the species' 'use_for' hint, but treat variety across the sequence as a hard requirement — "
                    "do not use the same species for more than 2-3 scenes in a row unless the narrative specifically "
                    "calls for the same plant to persist (e.g. a before/after comparison):\n"
                    f"{species_list}\n\n"
                    "HARD RULE: every single prompt must name one specific species from the list above, no exceptions. "
                    "If a scene's narration doesn't describe the plant's appearance at all (e.g. a general statement, "
                    "a transition line, or an abstract point like 'this weakens your plant's immune system'), you must "
                    "still pick a specific species — use the same species as the immediately preceding or following "
                    "scene if that keeps continuity, or pick one whose 'use_for' hint matches the scene's underlying "
                    "topic. NEVER write just 'succulent' or 'the plant' without naming a species — this rule applies "
                    "even to abstract or transitional narration lines.\n\n"
                    "STEP 2 — Also vary the SETTING and PROPS across scenes (home windowsill, backyard garden, "
                    "small nursery, horticulture room, florist, home plant room, etc.). Treat this as a hard "
                    "requirement, same as species: do not use the same setting for more than 2 scenes in a row, "
                    "and no single setting should appear in more than a third of all scenes in the sequence.\n\n"
                    "STEP 2.5 — If a scene's narration describes a specific physical action already happening "
                    "(pouring water, water flowing/soaking/draining, misting, repotting, trimming, checking roots, "
                    "propagating, etc.), the image MUST depict that exact action IN PROGRESS with visible evidence "
                    "— e.g. water actively pouring or streaming, visibly wet/soaked soil, water dripping from a "
                    "drainage hole. Do NOT soften this into a preparatory or generic gesture like 'hands about to "
                    "water' or 'checking the pot for drainage' when the narration says the action is already "
                    "happening — match the narration's specificity exactly. This rule is at least as important as "
                    "species/setting variety; never drop the action to make room for a variety fix.\n\n"
                    "STEP 3 — Build each image prompt using this template (replace [SPECIES] with the chosen "
                    "species name + common name):\n"
                    f"{style_template}\n\n"
                    "STEP 4 — Prepend the best camera descriptor for each scene:\n"
                    f"{camera_descriptor_block(config)}\n\n"
                    "Add highly specific visual detail — action, texture, sensory detail, lighting. Do not reuse the "
                    "same closing phrase (e.g. 'Rich earthy tones... No text, no logos. Photorealistic.') verbatim "
                    "across scenes — vary the sensory language scene to scene, the same way a photographer would "
                    "describe each shot differently.\n"
                    "  Good: 'dark, damp soil particles clinging to the skin, visually indicating moisture'\n"
                    "  Bad: 'person touching soil'\n\n"
                    "LIGHTING — the channel's identity is warm natural light ONLY (golden hour, soft window light, "
                    "warm ambient light). Never harsh, cold, blue-toned, or studio lighting — this is a hard brand "
                    "rule, not a stylistic default; it applies to every scene including distress/negative ones.\n"
                    "  - night / nighttime / 3 a.m. / nocturnal / 'opens its pores at night'  → soft moonlight is "
                    "the one accepted exception to the warm-only rule, since it's narratively necessary — keep it "
                    "gentle and atmospheric, not harsh or clinical\n"
                    "  - dusk / evening / winding down  → dimming, low warm light\n"
                    "  - resilience / thriving / triumph / healthy again  → golden hour\n"
                    "  - distress / dehydration / wilting / pest infestation / puckered or shriveled leaves / "
                    "immune system weakening / disease  → still WARM light (never harsh or cold), but convey the "
                    "distress through texture and color instead: duller/more desaturated warm tones, weaker or "
                    "filtered light (e.g. light through a dusty window), wilted/shriveled/discoloured plant texture, "
                    "muted terracotta and faded greens rather than vibrant colour. The mood should feel subdued, "
                    "not switch lighting style entirely.\n"
                    "If a scene mentions CAM photosynthesis, pores opening at night, or otherwise explicitly describes "
                    "nighttime behaviour, that scene's image should be the moonlight exception above — do not default "
                    "to daytime lighting for it just because a neighbouring scene is bright.\n\n"
                    "Show a real person genuinely engaged in the craft where it fits the scene — hands AND faces "
                    "are both welcome and encouraged. Do not default to the generic phrase 'a person' as filler — "
                    "describe what they're actually doing and how much of them is visible, concretely, e.g.: "
                    "'a woman's face in profile, focused as she checks a leaf for damage', 'a man glancing down at "
                    "his hands while he repots', 'someone's face softly lit as they inspect the soil'. A face can "
                    "be partially visible, in profile, half-turned away, or looking down at the work — natural and "
                    "candid, like someone caught mid-task, never posed at the camera. Vary how much of the person "
                    "is shown scene to scene (sometimes just hands, sometimes hands and a partial face, sometimes a "
                    "fuller candid shot) rather than repeating the same framing every time. No text overlays, no logos.\n\n"
                    "Use the channel brand brief (if provided below) as the authoritative source for tone, visual "
                    "identity, and species usage — it takes priority over any general instinct above if they ever "
                    "conflict. Use the full source document (if provided below) to understand the biological/"
                    "narrative point each scene is making.\n\n"
                    "Output ONLY a JSON object mapping each scene_id to its prompt string, like:\n"
                    f'{{"SCENE-001": "A {orientation_phrase(config)} ...", '
                    f'"SCENE-002": "A {orientation_phrase(config)} ..."}}\n'
                    "No commentary, no markdown fencing."
                    f"{brand_brief_block}"
                    f"{source_doc_block}"
                    f"{extra_instruction_block}"
                )
            }, {
                "role": "user",
                "content": f"Scenes (in order):\n{scenes_block}"
            }],
            temperature=0.7,
        )

        parsed = _json.loads(response.choices[0].message.content)
        return {sid: p.strip() for sid, p in parsed.items() if isinstance(p, str) and p.strip()}

    except Exception as e:
        print(f"   ⚠️  Batch prompt generation failed ({e}) — falling back to per-scene generation.")
        return {}


def _extract_setting(prompt: str, known_settings: list) -> str:
    """
    Identify which canonical location a generated prompt used, by matching
    against known setting keywords (channel_dna's validation.setting_vocabulary
    -- see Phase 1.5, BUILD_BRIEF_PHASE_1_5.md §1a) rather than the raw
    'Setting: ...' clause verbatim — different scenes describe the same location
    with different trailing modifiers (e.g. "home plant room, intimate" vs "home
    plant room, warm golden-hour light"), which would otherwise count as distinct
    settings and let real repetition slip past a literal-string check.

    Order in known_settings is load-bearing (first match wins) — the DNA file
    documents this; do not alphabetise it there.
    """
    lower = prompt.lower()
    for keyword in known_settings:
        if keyword in lower:
            return keyword
    # Fallback: raw clause, for anything using an unlisted setting
    m = re.search(r"Setting:\s*([^,.]+)", prompt, re.IGNORECASE)
    return m.group(1).strip().lower() if m else ""


def approved_species_list(config: dict) -> list:
    """
    Flatten config['subjects'] into a list of entries for names_species() to match
    against. Real shape (from <channel_dna>/*.json, merged into config by
    config_loader.py) is a dict keyed by canonical name, each value optionally
    carrying an "aliases" list (Phase 1.5, BUILD_BRIEF_PHASE_1_5.md — e.g.
    "Haworthiopsis fasciata" with alias "Haworthia fasciata", the older name it's
    still widely sold under). Also accepts list-of-str / list-of-dict defensively
    (no alias support in that fallback shape — it predates aliases and nothing
    currently produces it).

    Returns a list of either bare name strings (no aliases) or (canonical, [aliases])
    tuples. str(entry) callers must handle both — see the fix_note species_detail
    text below, which extracts just the canonical name for display.

    Renamed from "approved_species" to "subjects" as part of the channel_dna
    split (BUILD_BRIEF_PHASE_1_5.md §1g) -- this reader was updated in Phase 1,
    ahead of the rest of that phase's extraction work, because leaving it
    reading a now-nonexistent config key would silently break species
    validation rather than fail loudly.
    """
    raw = config.get("subjects", {})
    if isinstance(raw, dict):
        out = []
        for name, info in raw.items():
            if not name:
                continue
            aliases = info.get("aliases", []) if isinstance(info, dict) else []
            out.append((name, aliases) if aliases else name)
        return out
    out = []
    for s in raw:
        name = s if isinstance(s, str) else (s.get("name") or s.get("species"))
        if name:
            out.append(name)
    return out


def _canonical_name(entry) -> str:
    """entry is either a bare name string or a (canonical, [aliases]) tuple."""
    return entry if isinstance(entry, str) else entry[0]


def names_species(prompt: str, approved: list):
    """
    Return the CANONICAL name of the first approved species whose first two
    name-words — from the canonical name OR any alias — all appear as substrings
    of prompt (case-insensitive), or None. Checking only the first two words means
    cultivar punctuation/diacritics ("Echeveria 'Perle von Nurnberg'") never affect
    the match. Single source of truth -- audit_prompts.py imports this instead of
    keeping its own copy, so the two can't drift apart again.

    Matching on an alias still returns the canonical name (Phase 1.5) — a prompt
    naming only "Senecio rowleyanus" (the old trade name) is recognized as
    "Curio rowleyanus" (current name), so downstream code that treats the return
    value as *the* species identifier never sees two different strings for one
    plant.
    """
    prompt_l = prompt.lower()
    for entry in approved:
        canonical = _canonical_name(entry)
        aliases = entry[1] if isinstance(entry, tuple) else []
        for candidate in (canonical, *aliases):
            words = candidate.replace("'", "").split()[:2]
            if words and all(w.lower() in prompt_l for w in words):
                return canonical
    return None


def validate_and_fix_shots(shot_prompts: dict, shots_needing_gen: list, config: dict,
                           source_doc: str = "", brand_brief: str = "", max_retries: int = 2,
                           regenerate_fn=None) -> dict:
    """
    Programmatic check of batch-generated prompts against the numeric variety
    rules that plain prose instructions alone haven't reliably held (tested
    across three rounds: species/setting clustering, and a bare 'succulent'
    slipping through). Re-prompts ONLY the violating shots, with the specific
    violation called out, rather than regenerating everything.

    shot_prompts: dict {shot_key: prompt} — mutated in place and returned.
    shots_needing_gen: the same list passed to auto_generate_prompts_batch
    (list of {"id": ..., "script": ...}), used to re-issue a corrective call.
    regenerate_fn: optional callable(retry_shots, fix_note) -> {id: prompt}, used
    to rewrite violating shots. Defaults to auto_generate_prompts_batch. Callers
    with their own prompt style (generate_override_prompts.py) pass their own so
    corrected shots keep that style instead of reverting to this module's.
    """
    shots_by_id = {s["id"]: s for s in shots_needing_gen}

    # ── DNA-driven rule data (Phase 1.5, BUILD_BRIEF_PHASE_1_5.md) ──────────────
    # The rule ENGINE below (retry loop, overuse threshold, matching algorithms) is
    # subject-independent and stays in code — see §2 of the brief. Only the actual
    # succulent-specific vocabulary comes from <channel_dna>/<name>.json's "validation"
    # block now; a channel for a different subject supplies its own without touching
    # this function.
    validation = config.get("validation", {})

    subject_ref_cfg = validation.get("subject_reference_pattern", {})
    PLANT_REFERENCE_PATTERN = re.compile(
        subject_ref_cfg.get("pattern", r"\b(plants?|succulents?)\b"), re.IGNORECASE
    )
    # Diagnostic-print label, not sent to the model — see fix_note's species_detail below for
    # the model-facing text. Phase 1.5 follow-up: this used to be hardcoded English ("mentions
    # plant material..."), found leaking succulent-shaped wording into the console output for
    # an unrelated subject during the §6.7 portability check. Now DNA-sourced like everything
    # else in this block.
    no_species_label = subject_ref_cfg.get("label", "mentions subject material with no real species named")

    known_settings = validation.get("setting_vocabulary", {}).get("keywords", [])

    ACTION_CHECKS = [
        (c["narration"], c["evidence"], c["id"], c.get("guidance", ""),
         c.get("label", "narration describes an action not shown in the image"))
        for c in validation.get("action_checks", [])
    ]
    REVERSAL_CHECKS = [
        (c["narration"], c["evidence"], c["id"], c["reason"],
         c["evidence_must_be_absent"], c.get("guidance", ""))
        for c in validation.get("reversal_checks", [])
    ]
    HALLUCINATION_CHECKS = [
        (c["narration_must_lack"], c["evidence"], c["id"], c["reason"], c.get("guidance", ""))
        for c in validation.get("hallucination_checks", [])
    ]

    approved_species = approved_species_list(config)

    for attempt in range(max_retries):
        settings = {key: _extract_setting(p, known_settings) for key, p in shot_prompts.items() if p}
        total = len(settings)
        if total == 0:
            break

        counts = Counter(v for v in settings.values() if v)
        threshold = max(2, -(-total // 3))  # ceil(total/3), min 2 — "no more than a third"
        overused_settings = {s for s, c in counts.items() if c > threshold}

        # Only flag when the prompt mentions plant material at all -- a legitimate
        # plant-free soil/pot/mechanism shot must never be force-fed a species name.
        # Supersedes the old narrow "(a|the) succulent" regex (verified strict
        # superset, including its parenthetical-exemption behaviour); keeping both
        # would just be two overlapping checks that can drift apart again.
        no_species_keys = {
            key for key, p in shot_prompts.items()
            if p and PLANT_REFERENCE_PATTERN.search(p) and not names_species(p, approved_species)
        }

        action_mismatch_keys = set()
        fired_action_guidance = set()
        fired_action_labels = set()
        reversal_keys = set()
        reversal_reasons: dict[str, str] = {}
        fired_reversal_guidance = set()
        for key, prompt in shot_prompts.items():
            if not prompt or key not in shots_by_id:
                continue
            script_text = shots_by_id[key].get("script", "")
            for narration_pat, visual_pat, _rule_id, guidance, label in ACTION_CHECKS:
                if re.search(narration_pat, script_text, re.IGNORECASE) and \
                   not re.search(visual_pat, prompt, re.IGNORECASE):
                    action_mismatch_keys.add(key)
                    fired_action_labels.add(label)
                    if guidance:
                        fired_action_guidance.add(guidance)
            for narration_pat, evidence_pat, _rule_id, reason, evidence_must_be_absent, guidance in REVERSAL_CHECKS:
                if re.search(narration_pat, script_text, re.IGNORECASE):
                    evidence_found = bool(re.search(evidence_pat, prompt, re.IGNORECASE))
                    # Fire when evidence is present but shouldn't be (must_be_absent=True)
                    # OR when evidence is absent but must be present (must_be_absent=False)
                    if evidence_must_be_absent == evidence_found:
                        reversal_keys.add(key)
                        reversal_reasons[key] = reason
                        if guidance:
                            fired_reversal_guidance.add(guidance)
            for narration_keyword_pat, prompt_evidence_pat, _rule_id, reason, guidance in HALLUCINATION_CHECKS:
                if not re.search(narration_keyword_pat, script_text, re.IGNORECASE) and \
                   re.search(prompt_evidence_pat, prompt, re.IGNORECASE):
                    reversal_keys.add(key)
                    reversal_reasons[key] = reason
                    if guidance:
                        fired_reversal_guidance.add(guidance)

        setting_violations = {key for key, s in settings.items() if s in overused_settings}
        violating_keys = (setting_violations | no_species_keys | action_mismatch_keys | reversal_keys) & shots_by_id.keys()

        if not violating_keys:
            print(f"   ✅ Validation pass {attempt + 1}: no variety-rule violations found.")
            break

        reasons = []
        if setting_violations & shots_by_id.keys():
            reasons.append(f"setting(s) {', '.join(sorted(overused_settings))} overused "
                           f"({', '.join(sorted(setting_violations))})")
        if no_species_keys:
            reasons.append(f"{no_species_label} "
                           f"({', '.join(sorted(no_species_keys))})")
        if action_mismatch_keys:
            reasons.append(f"{'; '.join(sorted(fired_action_labels))} "
                           f"({', '.join(sorted(action_mismatch_keys))})")
        if reversal_keys:
            reasons.append(f"semantic reversal — prompt shows opposite/solution of what narration describes "
                           f"({'; '.join(f'{k}: {reversal_reasons[k]}' for k in sorted(reversal_keys))})")
        print(f"   🔎 Validation pass {attempt + 1}: {len(violating_keys)} shot(s) need fixing — {'; '.join(reasons)}")

        # fix_note is composed from ONLY the guidance of rules that actually fired —
        # Phase 1.5 §4. The model gets targeted correction instead of a wall of mostly-
        # irrelevant rules, and the guidance itself now lives in channel_dna, so a
        # different subject's DNA supplies its own guidance for its own rules.
        still_ok_settings = ", ".join(sorted(set(settings.values()) - overused_settings)) or "none used yet"
        fix_note_parts = []
        if setting_violations & shots_by_id.keys():
            fix_note_parts.append(
                f"The setting(s) {', '.join(sorted(overused_settings))} are already overused elsewhere in "
                f"this video — do NOT use them again for these shots. Pick a different setting instead "
                f"(already-used, still-fine options include: {still_ok_settings}, or another from the "
                f"approved list)."
            )
        if no_species_keys:
            approved_names = sorted({_canonical_name(sp) for sp in approved_species})
            fix_note_parts.append(
                f"These shots mention a plant but never name it: {', '.join(sorted(no_species_keys))}. "
                f"Name one specific species from this approved list for each: "
                f"{', '.join(approved_names)}. Never leave it as bare 'succulent' or 'the plant'."
            )
        for guidance in sorted(fired_action_guidance):
            fix_note_parts.append(guidance)
        for guidance in sorted(fired_reversal_guidance):
            fix_note_parts.append(guidance)
        fix_note = " ".join(fix_note_parts)

        retry_shots = [shots_by_id[k] for k in violating_keys]
        if regenerate_fn is None:
            fixed = auto_generate_prompts_batch(retry_shots, config, source_doc, brand_brief,
                                                extra_instruction=fix_note)
        else:
            fixed = regenerate_fn(retry_shots, fix_note)
        for key, prompt in fixed.items():
            if prompt:
                shot_prompts[key] = prompt

    return shot_prompts


# ── image generation ──────────────────────────────────────────────────────────

def generate_with_replicate(prompt: str, aspect_ratio: str = "9:16",
                            max_retries: int = 4) -> bytes:
    """Generate with Replicate Flux Dev. Auto-retries on 429 rate limit."""
    import replicate
    import re

    for attempt in range(max_retries):
        try:
            output = replicate.run(
                "black-forest-labs/flux-dev",
                input={
                    "prompt": prompt,
                    "aspect_ratio": aspect_ratio,
                    "output_format": "png",
                    "output_quality": 90,
                    "num_inference_steps": 28,
                    "guidance": 3.5,
                }
            )
            item = output[0] if isinstance(output, list) else output
            if hasattr(item, "read"):
                return item.read()
            else:
                with urllib.request.urlopen(str(item)) as resp:
                    return resp.read()

        except Exception as e:
            err = str(e)
            if "429" in err or "throttled" in err or "rate limit" in err.lower():
                # Parse "resets in ~Xs" from error message
                match = re.search(r"resets in ~(\d+)s", err)
                wait  = int(match.group(1)) + 2 if match else 12
                if attempt < max_retries - 1:
                    print(f"       ⏳ Rate limited — waiting {wait}s (attempt {attempt+1}/{max_retries})...")
                    time.sleep(wait)
                    continue
            raise  # Not a rate limit error, or out of retries


def generate_with_xai(prompt: str, aspect_ratio: str = "9:16") -> bytes:
    """
    Generate with xAI Grok Imagine. Returns raw image bytes.

    Requests native `aspect_ratio` at "2k" resolution via extra_body (not part of the
    standard OpenAI Images API schema, so it has to go through extra_body rather than a
    typed kwarg on client.images.generate()). At 16:9/2k this returns ~2048x1152 — a
    true landscape image, not a 1024x1024 square requiring crop-then-upscale. (Earlier
    versions of this function assumed xAI had no size/aspect control at all; that was
    stale — see BUILD_BRIEF.md §3d update, 2026-08-05.) normalize_image() still runs
    unconditionally on the result regardless, so this is a quality improvement, not a
    correctness dependency.
    """
    from openai import OpenAI
    import base64

    client = OpenAI(
        api_key=os.environ.get("XAI_API_KEY"),
        base_url="https://api.x.ai/v1",
    )

    xai_models = ["grok-imagine-image", "grok-imagine-image-quality"]
    last_err = None
    for model_name in xai_models:
        try:
            response = client.images.generate(
                model=model_name,
                prompt=prompt,
                n=1,
                extra_body={
                    "aspect_ratio": aspect_ratio,
                    "resolution": "2k",
                },
            )
            item = response.data[0]
            # Response may be URL or b64 depending on API version
            if getattr(item, "b64_json", None):
                return base64.b64decode(item.b64_json)
            elif getattr(item, "url", None):
                # xAI temp URLs require Authorization header to download
                import requests as req_lib
                headers = {"Authorization": f"Bearer {os.environ.get('XAI_API_KEY')}"}
                r = req_lib.get(item.url, headers=headers, timeout=60)
                r.raise_for_status()
                return r.content
            else:
                raise ValueError(f"xAI response has neither url nor b64_json: {item}")
        except Exception as e:
            last_err = e
            if "not-found" in str(e) or "404" in str(e) or "does not exist" in str(e):
                continue   # Try next model name
            raise          # Different error — surface it

    raise last_err


def generate_with_gemini(prompt: str, aspect_ratio: str = "9:16") -> bytes:
    """Generate with Google Gemini Imagen via AI Studio. Returns raw image bytes."""
    import google.generativeai as genai
    import base64

    genai.configure(api_key=os.environ.get("GEMINI_API_KEY"))
    model = genai.ImageGenerationModel("imagen-3.0-generate-002")
    result = model.generate_images(
        prompt=prompt,
        number_of_images=1,
        aspect_ratio=aspect_ratio,
    )
    image = result.images[0]
    # SDK returns PIL image or raw bytes depending on version
    if hasattr(image, "_pil_image"):
        import io
        buf = io.BytesIO()
        image._pil_image.save(buf, format="PNG")
        return buf.getvalue()
    elif hasattr(image, "image_bytes"):
        return image.image_bytes
    else:
        # Fallback: access via _image_bytes or raw_image_bytes attribute
        raw = getattr(image, "raw_image_bytes", None) or getattr(image, "_raw_image_bytes", None)
        if raw:
            return raw
        raise ValueError(f"Cannot extract bytes from Gemini image response: {dir(image)}")


def _parse_aspect_ratio(ratio_str: str) -> float:
    """'9:16' -> 0.5625, '16:9' -> 1.778 (width / height)."""
    w_str, h_str = ratio_str.split(":")
    return float(w_str) / float(h_str)


def crop_to_aspect(image_bytes: bytes, ratio_str: str = "9:16") -> bytes:
    """
    Centre-crop any image (square, landscape, or off-ratio) to a true
    `ratio_str` (e.g. "9:16", "16:9") frame. Always crops to fill — never
    pads with black bars, since a letterboxed image reads as wrong-orientation
    in the final video. Returns PNG bytes.

    Requires Pillow — raises ImportError if unavailable rather than silently
    returning uncropped bytes, since an uncropped off-ratio image is exactly
    the failure this function exists to prevent (see BUILD_BRIEF.md §3c2).
    """
    from PIL import Image
    import io
    img = Image.open(io.BytesIO(image_bytes)).convert("RGB")
    w, h = img.size
    target_ratio = _parse_aspect_ratio(ratio_str)

    current_ratio = w / h
    if current_ratio > target_ratio:
        # Too wide relative to target — crop width, keep full height
        new_w = int(h * target_ratio)
        left = (w - new_w) // 2
        img = img.crop((left, 0, left + new_w, h))
    elif current_ratio < target_ratio:
        # Too tall/narrow relative to target — crop height, keep full width
        new_h = int(w / target_ratio)
        top = (h - new_h) // 2
        img = img.crop((0, top, w, top + new_h))
    # else: already exactly the target ratio, no crop needed

    buf = io.BytesIO()
    img.save(buf, format="PNG")
    return buf.getvalue()


def normalize_image(image_bytes: bytes, ratio_str: str = "9:16",
                     target_resolution: str = None) -> bytes:
    """
    Crop to `ratio_str`, then resize to `target_resolution` ("WxH", e.g.
    "1920x1080"). Applied to EVERY generated image regardless of provider —
    per BUILD_BRIEF.md §3c2, this is what actually guarantees correct output,
    not the provider order (§3d is a quality preference on top of this, not a
    correctness dependency).

    Raises loudly (ImportError, ValueError) instead of swallowing failures —
    the sibling pipeline's equivalent (`interested_indian_pipeline/
    generate_images_flux.py:277-278`) does `except Exception: pass`, which
    silently no-ops when PIL is missing and ships an un-normalized image with
    no error. That failure mode is exactly what this function must not repeat.
    """
    image_bytes = crop_to_aspect(image_bytes, ratio_str)

    if not target_resolution:
        return image_bytes

    from PIL import Image
    import io
    target_w, target_h = (int(x) for x in target_resolution.lower().split("x"))
    img = Image.open(io.BytesIO(image_bytes)).convert("RGB")
    if img.size != (target_w, target_h):
        img = img.resize((target_w, target_h), Image.LANCZOS)
    buf = io.BytesIO()
    img.save(buf, format="PNG")
    return buf.getvalue()


def save_image(image_bytes: bytes, path: str,
                aspect_ratio: str = "9:16", target_resolution: str = None):
    """
    Every image is normalized (cropped to aspect_ratio, resized to
    target_resolution) regardless of provider — see normalize_image(). There
    is no longer an is_square special case: normalization makes output
    correct unconditionally, so provider choice is a quality preference
    (BUILD_BRIEF.md §3d), not a correctness dependency.
    """
    image_bytes = normalize_image(image_bytes, aspect_ratio, target_resolution)
    with open(path, "wb") as f:
        f.write(image_bytes)


# ── main ──────────────────────────────────────────────────────────────────────

def generate_images(project_dir: str, force: bool = False, source_doc_path: str = None,
                    prompts_file: str = None, dry_run_prompts: bool = False,
                    workers: int = 4):
    manifest_path = os.path.join(project_dir, "manifest.json")
    if not os.path.exists(manifest_path):
        print(f"❌ manifest.json not found in {project_dir}")
        print("   Run auto_split_scenes.py first.")
        sys.exit(1)

    with open(manifest_path, "r", encoding="utf-8") as f:
        manifest = json.load(f)

    scripts_dir = os.path.dirname(os.path.abspath(__file__))
    config = load_config(scripts_dir)

    scenes            = manifest.get("scenes", [])
    aspect            = config.get("image_aspect_ratio", "9:16")
    target_resolution = config.get("image_target_resolution")
    images_dir        = os.path.join(project_dir, "images")
    os.makedirs(images_dir, exist_ok=True)

    has_replicate = bool(os.environ.get("REPLICATE_API_TOKEN"))
    has_xai       = bool(os.environ.get("XAI_API_KEY"))
    has_openai    = bool(os.environ.get("OPENAI_API_KEY"))
    has_gemini    = bool(os.environ.get("GEMINI_API_KEY"))

    if not has_replicate and not has_xai and not has_gemini:
        print("❌ No image provider configured. Set XAI_API_KEY, REPLICATE_API_TOKEN, or GEMINI_API_KEY.")
        sys.exit(1)

    # Provider order + availability. "image_provider_order" is config-driven so a config
    # naming a provider by its config-key ("xai") can't silently disagree with code that
    # checks a different string ("Flux Dev") — see BUILD_BRIEF.md §3d. Default preserves
    # today's Shorts behavior (xAI first) for any config that doesn't set this key.
    # returns_square is informational only (logged, not branched on) — normalize_image()
    # crops/resizes every image unconditionally regardless of provider, see save_image()/
    # BUILD_BRIEF.md §3c2. xAI is no longer square: it now requests native aspect_ratio
    # at "2k" via extra_body (~2048x1152 at 16:9), not the 1024x1024 square earlier
    # code assumed — see generate_with_xai()'s docstring.
    PROVIDER_REGISTRY = {
        "xai":       {"label": "xAI",      "available": has_xai,       "returns_square": False},
        "replicate": {"label": "Flux Dev", "available": has_replicate, "returns_square": False},
        "gemini":    {"label": "Gemini",   "available": has_gemini,    "returns_square": False},
    }
    provider_order = [
        key for key in config.get("image_provider_order", ["xai", "replicate", "gemini"])
        if key in PROVIDER_REGISTRY and PROVIDER_REGISTRY[key]["available"]
    ]
    if not provider_order:
        print("❌ No configured provider in image_provider_order has a usable API key.")
        sys.exit(1)

    # ── Build "shots": scenes sharing a visual_group_id share ONE image ──────
    # auto_split_scenes.py already detects fragment groups (e.g. "Sign 1." +
    # "Translucent leaves." + "If they look glassy..." = one visual idea), and
    # stitch_video_complete.py already falls back to images/{visual_group_id}.png
    # when a scene-level image doesn't exist for a grouped scene. This was the
    # only piece not wired up — image generation used to make one distinct
    # image per scene regardless of grouping, defeating the purpose.
    shots = []
    shots_by_key = {}
    for scene in scenes:
        key = scene.get("visual_group_id") or scene["id"]
        if key not in shots_by_key:
            shot = {"key": key, "is_group": bool(scene.get("visual_group_id")), "members": []}
            shots_by_key[key] = shot
            shots.append(shot)
        shots_by_key[key]["members"].append(scene)

    n_grouped_shots = sum(1 for s in shots if s["is_group"])
    if n_grouped_shots:
        print(f"   🔗 {n_grouped_shots} visual group(s) detected — each will share ONE image "
              f"across its member scenes instead of one image per scene.")

    # Build prompt map (per scene_id — respects manifest / --prompts-file / script_prompts.json priority)
    print(f"\n🗺️  Building image prompts for {len(scenes)} scenes ({len(shots)} unique shots)...")
    prompt_map = build_prompt_map(project_dir, scenes, prompts_file)

    # Resolve each shot's prompt (first resolved prompt among its members, if any)
    # and its combined narration text (used if it needs auto-generation).
    for shot in shots:
        shot["prompt"] = next(
            (prompt_map.get(m["id"]) for m in shot["members"] if prompt_map.get(m["id"])), None
        )
        shot["combined_script"] = " ".join(m.get("script", "") for m in shot["members"])

    # Auto-generate missing prompts, one call covering all shots that need one
    missing_shots = [s for s in shots if not s["prompt"]]
    if missing_shots:
        if has_openai:
            source_doc = load_source_doc(project_dir, source_doc_path, config=config)
            brand_brief = load_brand_brief(scripts_dir)
            tag = " (with source-doc context)" if source_doc else ""
            tag += " + brand brief" if brand_brief else ""
            print(f"   Auto-generating prompts for {len(missing_shots)} shots via OpenAI{tag}...")

            print(f"   Trying batch generation (full cross-scene variety awareness)...")
            shots_for_gen = [{"id": s["key"], "script": s["combined_script"]} for s in missing_shots]
            batch_prompts = auto_generate_prompts_batch(shots_for_gen, config, source_doc, brand_brief)

            # Programmatic validation/retry pass — prose instructions alone
            # didn't reliably hold up across setting-repetition and generic-
            # species checks in testing, so verify and re-prompt violators.
            batch_prompts = validate_and_fix_shots(batch_prompts, shots_for_gen, config, source_doc, brand_brief)

            for shot in missing_shots:
                if shot["key"] in batch_prompts:
                    shot["prompt"] = batch_prompts[shot["key"]]
                else:
                    print(f"      ↳ {shot['key']} missing from batch result — generating individually")
                    shot["prompt"] = auto_generate_prompt(shot["combined_script"], config, source_doc, brand_brief)
        else:
            print(f"   ⚠️  {len(missing_shots)} shots have no prompts and OPENAI_API_KEY is not set.")
            print("      Add a 'prompt' field to each scene in manifest.json, or set OPENAI_API_KEY.")
            for shot in missing_shots:
                style = config.get("image_style", "Macro photography, succulents, warm light.")
                shot["prompt"] = f"{shot['combined_script'] or 'succulent plant'}. {style}"

    # ── Dry-run: write prompts for review, then exit ──────────────────────────
    if dry_run_prompts:
        review_path = os.path.join(project_dir, "prompts_review.json")
        review_entries = []
        for shot in shots:
            entry = {
                "scene_id": shot["key"],
                "script": shot["combined_script"],
                "auto_prompt": shot["prompt"] or "",
                "override_prompt": "",   # fill this in to override; leave blank to use auto_prompt
            }
            review_entries.append(entry)

        with open(review_path, "w", encoding="utf-8") as f:
            json.dump({"image_prompts": review_entries}, f, indent=2, ensure_ascii=False)

        print(f"\n{'═' * 60}")
        print(f"✅ DRY RUN — prompts written, no images generated.")
        print(f"{'═' * 60}")
        print(f"\n  📝 Review file: {review_path}")
        print(f"\n  For each scene, either:")
        print(f"    • leave 'override_prompt' blank → auto_prompt will be used as-is")
        print(f"    • fill in 'override_prompt'    → your text will be used instead")
        print(f"\n  When ready, run image generation with:")
        print(f"    python generate_images.py --project {os.path.basename(project_dir)} "
              f"--prompts-file {review_path}")
        print(f"\n  Or via the full pipeline:")
        print(f"    python run_pipeline.py --project <name> --variants yt "
              f"--start-from images --prompts-file {review_path}")
        print()
        return

    # ── Generate images, fanned out across a small thread pool ───────────────
    # Each shot's image is fully independent (own prompt, own output file, no shared
    # state between them) — mirrors interested_indian_pipeline/generate_images_flux.py's
    # ThreadPoolExecutor pattern instead of one request + time.sleep(11) at a time.
    # generate_with_replicate() already retries 429s internally (max_retries=4), so no
    # extra backoff is needed here just because requests aren't sequential.
    #
    # Thread-safety: _generate_one() below only calls providers and writes its own
    # unique image file — no shared state touched from worker threads. All manifest
    # mutation and the success/failed counters happen back in the main thread, in the
    # as_completed() loop, exactly like the sibling pipeline's own summary loop.
    print(f"\n🖼️  Generating images (order: "
          f"{' → '.join(PROVIDER_REGISTRY[k]['label'] for k in provider_order)}, "
          f"{workers} worker(s))...\n")
    if target_resolution:
        print(f"   Normalizing every image to {aspect} @ {target_resolution}\n")
    success = 0
    failed  = []
    updated_scenes = False

    def _generate_one(shot):
        prompt = shot["prompt"] or ""
        image_path = os.path.join(images_dir, f"{shot['key']}.png")
        image_bytes = None
        provider    = None
        warnings    = []

        for provider_key in provider_order:
            entry = PROVIDER_REGISTRY[provider_key]
            try:
                if provider_key == "xai":
                    image_bytes = generate_with_xai(prompt, aspect_ratio=aspect)
                elif provider_key == "replicate":
                    import replicate  # noqa
                    image_bytes = generate_with_replicate(prompt, aspect_ratio=aspect)
                elif provider_key == "gemini":
                    image_bytes = generate_with_gemini(prompt, aspect_ratio=aspect)
                provider = entry["label"]
                break
            except Exception as e:
                warnings.append(f"{entry['label']} failed: {e}")

        if image_bytes is None:
            return shot, prompt, None, None, warnings

        save_image(image_bytes, image_path, aspect_ratio=aspect,
                   target_resolution=target_resolution)
        file_kb = os.path.getsize(image_path) // 1024
        return shot, prompt, provider, file_kb, warnings

    to_generate = []
    for i, shot in enumerate(shots, 1):
        image_path = os.path.join(images_dir, f"{shot['key']}.png")
        label = f"{shot['key']} ({len(shot['members'])} scenes: {', '.join(m['id'] for m in shot['members'])})" \
                if shot["is_group"] else shot["key"]

        if os.path.exists(image_path) and not force:
            print(f"   [{i}/{len(shots)}] {label}  ⏭  already exists, skipping")
            success += 1
            continue

        print(f"   [{i}/{len(shots)}] {label} — queued")
        print(f"       Prompt: {(shot['prompt'] or '')[:80]}"
              f"{'...' if len(shot['prompt'] or '') > 80 else ''}")
        to_generate.append(shot)

    if to_generate:
        with ThreadPoolExecutor(max_workers=max(1, workers)) as pool:
            futures = {pool.submit(_generate_one, shot): shot for shot in to_generate}
            for future in as_completed(futures):
                shot, prompt, provider, file_kb, warnings = future.result()
                for w in warnings:
                    print(f"       ⚠️  [{shot['key']}] {w}")

                if provider is None:
                    print(f"       ❌ All providers failed for {shot['key']}")
                    failed.append(shot["key"])
                    continue

                image_path = os.path.join(images_dir, f"{shot['key']}.png")
                print(f"       ✅ [{shot['key']}] {provider}  →  {image_path}  ({file_kb} KB)")

                # Write the shared prompt back to every member scene, for reference. Always
                # sync it — this code path only runs right after a fresh generation (existing
                # images are skipped above), so `prompt` is always exactly what was just used.
                # A "only if not already set" guard here would silently leave a stale prompt
                # in the manifest whenever an explicit --prompts-file override legitimately
                # supersedes an earlier cached value, which is exactly what it did once.
                for m in shot["members"]:
                    if m.get("prompt") != prompt:
                        m["prompt"] = prompt
                        updated_scenes = True

                success += 1

    # Save updated manifest (with prompts written back)
    if updated_scenes:
        with open(manifest_path, "w", encoding="utf-8") as f:
            json.dump(manifest, f, indent=2, ensure_ascii=False)
        print(f"\n   📝 Prompts written back to manifest.json")

    print(f"\n{'─'*50}")
    print(f"✅ Done: {success}/{len(shots)} images generated, covering {len(scenes)} scenes")
    if failed:
        print(f"❌ Failed: {', '.join(failed)}")
        print(f"   Add these images manually to {images_dir}")
    print(f"{'─'*50}\n")
    return len(failed) == 0


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Generate scene images for an AeoniumGlow Short")
    parser.add_argument("--project", required=True, help="Project folder (e.g. short-04)")
    parser.add_argument("--force", action="store_true", help="Re-generate images that already exist")
    parser.add_argument("--source-doc", default=None,
                        help="Path to the long-form video source document (.md/.txt), given to the "
                             "auto-prompt generator as story context. If omitted, auto-detects a "
                             "single .md/.txt file in {project}/source_doc/ if present.")
    parser.add_argument("--prompts-file", default=None,
                        help="Path to a JSON file of hand-written prompts, same schema as "
                             "script_prompts.json (a list under 'image_prompts', each entry with "
                             "a 'scene_id' and 'prompt'). Also accepts the prompts_review.json "
                             "format — fill 'override_prompt' to override, leave blank to use "
                             "the auto-generated prompt. A per-scene 'prompt' already set in "
                             "manifest.json still wins over this file.")
    parser.add_argument("--dry-run-prompts", action="store_true",
                        help="Generate and validate all image prompts, write them to "
                             "prompts_review.json for manual review, then exit WITHOUT generating "
                             "any images. Edit the file, then re-run with "
                             "--prompts-file prompts_review.json to produce the images.")
    parser.add_argument("--workers", type=int, default=4,
                        help="Concurrent image-generation requests (default: 4). Each shot's "
                             "image is independent, so this is safe to raise; lower it if a "
                             "provider starts rate-limiting.")
    args = parser.parse_args()

    scripts_dir  = os.path.dirname(os.path.abspath(__file__))
    project_dir  = (
        args.project if os.path.isabs(args.project)
        else os.path.join(scripts_dir, args.project)
    )

    if not os.path.isdir(project_dir):
        print(f"❌ Project folder not found: {project_dir}")
        sys.exit(1)

    generate_images(project_dir, force=args.force, source_doc_path=args.source_doc,
                    prompts_file=args.prompts_file, dry_run_prompts=args.dry_run_prompts,
                    workers=args.workers)
